/* Private profile and integration controls. No external scripts or credentials in assets. */
(() => {
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const json = v => JSON.stringify(v ?? [], null, 2);
  const editor = (label, id, value, rows=5) => `<label>${label}<textarea id="${id}" rows="${rows}" spellcheck="false">${esc(json(value))}</textarea></label>`;
  const field = (label,id,value,type='text') => `<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
  function profile(state) {
    const p=state.profile;
    return `<section class="panel detail-section"><h2>Your master profile</h2><p>Save confirmed facts here. Fit reviews use this profile; connected services receive factual update tasks. Revision <strong>${esc(p.revision||1)}</strong>.</p><form id="master-profile-form"><div class="two-columns">${field('Name','profile-name',p.name)}${field('Headline','profile-headline',p.headline||'')}</div><label>Summary<textarea id="profile-summary" rows="3">${esc(p.summary)}</textarea></label><label>Skills (one per line)<textarea id="profile-skills" rows="4">${esc((p.skills||[]).join('\n'))}</textarea></label><details><summary>Education, experience and projects</summary><p class="muted">These structured fields use JSON. Preserve dates and distinguish professional, internship and academic work.</p>${editor('Contact details','profile-contact',p.contact||{})}${editor('Education','profile-education',p.education||{})}${editor('Experience','profile-experience',p.experience||[])}${editor('Projects','profile-projects',p.projects||[])}</details><details><summary>Evidence and search preferences</summary><p class="muted">Evidence needs a unique id, source and claim. A listed skill alone does not establish professional ownership.</p>${editor('Supporting evidence','profile-evidence',p.evidence||[],8)}${editor('Search preferences and confirmed authorization details','profile-preferences',p.preferences||{},8)}</details><h3>Active resume</h3><p>${esc(p.activeResume?.filename||'No active resume uploaded')} ${esc(p.activeResume?.version||'')}</p><label>Upload PDF or DOCX (maximum 2 MB)<input id="profile-resume" type="file" accept=".pdf,.docx"></label>${field('Resume version','profile-resume-version',p.activeResume?.version||'')}<p class="muted"><button id="download-active-resume" type="button" class="secondary">Download active resume</button> Files stay in your local workspace or private browser storage. External resume uploads remain in the service update queue.</p><button class="primary" type="submit">Save master profile</button><span id="profile-save-status" role="status"></span></form></section><section class="panel detail-section"><h2>Quinncia analysis</h2><p>Use your college access for an additional review. Import its report here; it supplements the local fit review.</p><label>Report text<textarea id="quinncia-text" rows="4" placeholder="Paste your report or its relevant gap findings"></textarea></label><button class="secondary" id="save-quinncia">Save report privately</button><p class="muted">${(p.quinnciaReports||[]).length} saved reports. No public Quinncia API is configured.</p><a href="https://quinncia.io/" target="_blank" rel="noopener noreferrer">Open Quinncia</a></section>`;
  }
  function services(state) {
    const accounts=state.service_accounts||[], registry=state.job_services||[], tasks=state.sync_tasks||[];
    return `<section class="fit-strip"><div><strong>Your profile, five services</strong><p>Reuse existing accounts first. Sign in yourself; factual updates are queued for supported or browser-assisted workflows. A queue entry is not a completed external update.</p></div></section><div class="source-grid">${registry.filter(s=>s.tier==='launch'||s.tier==='conditional').map(s=>{
      const a=accounts.find(a=>a.provider===s.id)||{}, queue=tasks.filter(t=>t.provider===s.id&&!['completed','superseded'].includes(t.status));
      return `<article class="source-card"><h2>${esc(s.name)}</h2><p>${esc(s.why||s.description||(s.features||[]).join(' · '))}</p><p class="pill">${esc(a.status||'needs_action')}</p><p class="muted">${esc(s.contentPolicy||s.action||'Profile sync requires a supported integration or signed-in browser session.')}</p><a href="${esc(s.profile_url||s.url)}" target="_blank" rel="noopener noreferrer">Open account / sign in</a><label>Account state<select data-account-status="${esc(s.id)}">${['needs_action','needs_login','ready','paused'].map(x=>`<option value="${x}" ${a.status===x?'selected':''}>${esc(x.replaceAll('_',' '))}</option>`).join('')}</select></label><label>Existing account?<select data-account-exists="${esc(s.id)}"><option value="unknown">Check first</option><option value="yes" ${a.accountExists===true?'selected':''}>Yes — reuse it</option><option value="no" ${a.accountExists===false?'selected':''}>No — setup needed</option></select></label>${s.tier==='conditional'?`<label><input type="checkbox" data-confirm-access="${esc(s.id)}" ${a.availabilityConfirmed?'checked':''}>I confirmed university access; enable this service</label>`:''}<label>Profile URL (optional)<input data-account-url="${esc(s.id)}" type="url" value="${esc(a.profileUrl||'')}"></label><button class="secondary" data-save-account="${esc(s.id)}">Save account state</button><p>${queue.length} pending update task(s). Recruiter visibility: visible where supported.</p>${queue.map(t=>`<details><summary>Profile revision ${esc(t.profile_revision??t.profileRevision)} · ${esc(t.status)}</summary><pre class="sync-payload">${esc(json(t.facts||t.payload||t.changes||{}))}</pre><label>Update evidence / note<input data-sync-note="${esc(t.id)}" placeholder="What was updated, and where?"></label><button class="small-button" data-complete-sync="${esc(t.id)}" data-sync-revision="${esc(t.profile_revision??t.profileRevision)}">Record completed update</button></details>`).join('')}</article>`;
    }).join('')}</div><section class="panel detail-section"><h2>Job-alert inbox</h2><p>Imports only recognized job-alert messages from the last 30 days initially. Unrelated mail is excluded. Google’s read-only permission still covers the mailbox; this application applies the narrower filter.</p><p id="gmail-state">${esc(state.integrations?.gmail?.status||'Needs action: connect Gmail on this laptop')}</p><label>Google Desktop OAuth client JSON<input type="file" id="gmail-client" accept=".json"></label><div class="button-row"><button id="gmail-connect" class="secondary">Connect read-only Gmail</button><button id="gmail-sync" class="primary">Import job alerts now</button><button id="gmail-disconnect" class="secondary">Disconnect Gmail on this laptop</button><button id="integration-status" class="secondary">Refresh connection status</button></div><p class="muted">Sign in in Google’s authorization window. Credentials remain protected on this laptop and are excluded from backups.</p><h3>Local schedule</h3><p>Hourly imports while awake. Deep reviews: 2–6 a.m. Pacific, plugged in and idle. Unvalidated AI remains advisory; unattended ranking stays disabled until evaluation passes.</p><pre id="worker-state">${esc(json(state.integrations?.worker||{}))}</pre></section>`;
  }
  async function bind(state, {api,load,message}) {
    const q=s=>document.querySelector(s);
    const form=q('#master-profile-form');
    if(form)form.onsubmit=async e=>{
      e.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;
      try {
        const patch={name:q('#profile-name').value,headline:q('#profile-headline').value,summary:q('#profile-summary').value,skills:q('#profile-skills').value.split('\n').map(x=>x.trim()).filter(Boolean),contact:JSON.parse(q('#profile-contact').value),education:JSON.parse(q('#profile-education').value),experience:JSON.parse(q('#profile-experience').value),projects:JSON.parse(q('#profile-projects').value),evidence:JSON.parse(q('#profile-evidence').value),preferences:JSON.parse(q('#profile-preferences').value)};
        const file=q('#profile-resume').files[0];
        if(file){if(file.size>2*1024*1024||!(/\.(pdf|docx)$/i.test(file.name)))throw Error('Choose a PDF or DOCX of at most 2 MB.');const bytes=new Uint8Array(await file.arrayBuffer()),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));patch.activeResume={filename:file.name,version:q('#profile-resume-version').value||new Date().toISOString().slice(0,10),sha256:hash,mime_type:file.name.toLowerCase().endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};await api('/api/resume',{...patch.activeResume,data_base64:btoa(binary)});}else if(state.profile.activeResume){patch.activeResume={...state.profile.activeResume,version:q('#profile-resume-version').value};}
        await api('/api/profile',{patch,expected_revision:state.profile.revision||1});await load();message('Profile saved. Old fit reviews need a fresh review; external updates are queued.');
      }catch(e){message(e instanceof SyntaxError?'A structured profile field contains invalid JSON. Your edits have been kept.':e.message,true)}finally{button.disabled=false;}
    };
    q('#download-active-resume')?.addEventListener('click',async()=>{try{const r=await api('/api/resume');if(!r?.data_base64)throw Error('No active resume contents are stored here.');const bytes=Uint8Array.from(atob(r.data_base64),x=>x.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:r.mime_type||'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=state.profile.activeResume.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){message(e.message,true)}});
    q('#save-quinncia')?.addEventListener('click',async()=>{try{const text=q('#quinncia-text').value.trim();if(!text||text.length>50000)throw Error('Enter report text of up to 50,000 characters.');await api('/api/profile',{expected_revision:state.profile.revision||1,patch:{quinnciaReports:[...(state.profile.quinnciaReports||[]),{text,imported_at:new Date().toISOString(),source:'Quinncia college report'}]}});await load();message('Quinncia report saved privately.')}catch(e){message(e.message,true)}});
    document.querySelectorAll('[data-save-account]').forEach(b=>b.onclick=async()=>{try{const provider=b.dataset.saveAccount,exists=q(`[data-account-exists="${provider}"]`).value,access=q(`[data-confirm-access="${provider}"]`);await api('/api/services/account',{provider,status:q(`[data-account-status="${provider}"]`).value,profileUrl:q(`[data-account-url="${provider}"]`).value,accountExists:exists==='unknown'?null:exists==='yes',...(access?{enabled:access.checked,availabilityConfirmed:access.checked}:{})});await load();message('Account state saved. No external profile update is implied.')}catch(e){message(e.message,true)}});
    document.querySelectorAll('[data-complete-sync]').forEach(b=>b.onclick=async()=>{try{const note=q(`[data-sync-note="${b.dataset.completeSync}"]`).value.trim();if(!note)throw Error('Describe the update you completed before marking it done.');await api('/api/services/complete',{task_id:b.dataset.completeSync,profile_revision:Number(b.dataset.syncRevision),evidence:note});await load();message('Update completion recorded for this profile revision.')}catch(e){message(e.message,true)}});
    q('#gmail-connect')?.addEventListener('click',async()=>{try{const file=q('#gmail-client').files[0];if(!file||file.size>50000)throw Error('Choose your Google Desktop OAuth client JSON.');const result=await api('/api/gmail/connect',{client_config:JSON.parse(await file.text())});if(result.authorization_url){const a=document.createElement('a');a.href=result.authorization_url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Open Google authorization';q('#gmail-state').replaceChildren(a);a.click();}else message(result.status||'Google authorization started.');}catch(e){message(e.message,true)}});
    q('#gmail-sync')?.addEventListener('click',async()=>{try{const r=await api('/api/gmail/sync',{});message(r.error||(r.status==='Needs action'?(r.note||'Connect Gmail first.'):`Imported ${r.imported??r.jobs_imported??0} job-alert leads.`),!!r.error);await load()}catch(e){message(e.message,true)}});
    q('#gmail-disconnect')?.addEventListener('click',async()=>{try{const r=await api('/api/gmail/disconnect',{});await load();message(r.note||'Gmail disconnected on this laptop. Revoke access in Google settings to revoke the grant too.')}catch(e){message(e.message,true)}});
    q('#integration-status')?.addEventListener('click',async()=>{try{state.integrations=await api('/api/integrations');q('#gmail-state').textContent=state.integrations.gmail.status;q('#worker-state').textContent=json(state.integrations.worker);}catch(e){message(e.message,true)}});
  }
  window.WorkspaceUI={profile,services,bind};
})();
