/* Hosted equivalents for versioned profile edits and private source outcomes. */
(() => {
  const record=v=>!!v&&typeof v==='object'&&!Array.isArray(v);
  const cleanFields=['name','headline','summary','education','experience','projects','skills','preferences','evidence','activeResume','quinnciaReports','contact','earnedCredentials','trainingOnly'];
  const stamp=()=>new Date().toISOString();
  async function digest(v){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(v))))).map(x=>x.toString(16).padStart(2,'0')).join('');}
  function validate(p){
    if(!record(p)||Object.keys(p).some(k=>!cleanFields.includes(k)))throw Error('Unsupported profile field');
    const inspect=(v,depth=0)=>{if(depth>12)throw Error('Profile is too complex');if(typeof v==='string'&&v.length>50000)throw Error('Profile text too long');if(record(v)){for(const [k,x]of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(k)||['password','accesstoken','refreshtoken','apikey','clientsecret'].includes(k.toLowerCase().replaceAll('_','')))throw Error('Unsafe profile key or credential');inspect(x,depth+1)}}else if(Array.isArray(v)){if(v.length>1000)throw Error('Profile list too long');for(const x of v)inspect(x,depth+1)}};inspect(p);
    if(JSON.stringify(p).length>500000)throw Error('Profile exceeds size limit');
    for(const k of ['name','headline','summary'])if(k in p&&(typeof p[k]!=='string'||p[k].length>(k==='summary'?12000:300)))throw Error('Invalid '+k);
    if('name' in p&&!p.name.trim())throw Error('Name is required');
    for(const k of ['experience','projects','evidence','quinnciaReports'])if(k in p&&(!Array.isArray(p[k])||p[k].some(x=>!record(x))))throw Error(k+' must be a list of objects');
    for(const k of ['education','preferences','contact'])if(k in p&&!record(p[k]))throw Error(k+' must be an object');if('activeResume' in p&&p.activeResume!==null&&!record(p.activeResume))throw Error('activeResume must be metadata or null');
    if('skills' in p&&(!Array.isArray(p.skills)||p.skills.some(x=>typeof x!=='string'||!x.trim()||x.length>200)))throw Error('Invalid skills');
    if(p.evidence){const ids=new Set;for(const e of p.evidence){if(typeof e.id!=='string'||!e.id||ids.has(e.id)||typeof e.claim!=='string'||!e.claim.trim()||typeof e.source!=='string'||!e.source.trim())throw Error('Evidence needs unique id, source and claim');ids.add(e.id)}}
    if(p.activeResume&&(!/^[a-f0-9]{64}$/.test(p.activeResume.sha256||'')||!/^.{1,255}\.(pdf|docx)$/i.test(p.activeResume.filename||'')))throw Error('Invalid active resume metadata');
    if(p.activeResume&&Object.keys(p.activeResume).some(k=>!['filename','version','sha256','mime_type'].includes(k)))throw Error('activeResume accepts metadata only');
  }
  const merge=(a,b)=>{const out=structuredClone(a);for(const[k,v]of Object.entries(b))out[k]=record(v)&&record(out[k])?merge(out[k],v):structuredClone(v);return out;};
  const facts=p=>({name:p.name,headline:p.headline||'',summary:p.summary||'',education:p.education||{},experience:p.experience||[],projects:p.projects||[],skills:p.skills||[],contact:p.contact||{},activeResume:p.activeResume||null,preferences:Object.fromEntries(['country','opportunityTypes','relocation','remotePreference','salaryMin'].filter(k=>k in(p.preferences||{})).map(k=>[k,p.preferences[k]])),manualConfirmations:['Current authorization and EAD dates','Future sponsorship answer','Account visibility']});
  function init(d,registry){d.profile.revision??=1;d.service_accounts??=registry.filter(s=>s.tier==='launch').map(s=>({provider:s.id,status:'needs_login',enabled:true,accountExists:null,visibility:'recruiter_visible',profileUrl:'',updated_at:stamp()}));d.sync_tasks??=[];d.source_events??=[];d.job_services=registry;for(const t of d.sync_tasks){t.profile_revision??=t.profileRevision;t.payload??=t.facts;}for(const a of d.service_accounts){a.enabled??=true;if(!d.sync_tasks.some(t=>t.provider===a.provider)&&a.enabled&&a.status!=='paused')d.sync_tasks.push({id:crypto.randomUUID(),provider:a.provider,profile_revision:d.profile.revision,status:'needs_login',payload:facts(d.profile),created_at:stamp()});}}
  async function saveProfile(d,body,registry){
    if(!record(body)||!Number.isInteger(body.expected_revision)||body.expected_revision!==(d.profile.revision||1))throw Error('Profile changed. Reload before saving your edits.');validate(body.patch);
    const changedFields=Object.keys(body.patch).filter(k=>JSON.stringify(d.profile[k])!==JSON.stringify(body.patch[k]));if(!changedFields.length)return {profile:d.profile,changedFields:[],syncTasks:[]};
    const previous=d.profile,next={...merge(d.profile,body.patch),revision:(d.profile.revision||1)+1,savedAt:stamp()},fitChanged=changedFields.some(k=>k!=='quinnciaReports');if(fitChanged)next.profileVersion='workspace-r'+next.revision;next.profileHash=await digest(Object.fromEntries(Object.entries(next).filter(([k])=>!['profileHash','savedAt','revision'].includes(k))));d.profile=next;
    if(fitChanged)for(const j of d.jobs){j.assessment_stale=true;if(j.manual_fit)j.manual_fit_stale=true;}
    if(body.patch.preferences){if('country' in body.patch.preferences)d.preferences.country=next.preferences.country;if('salaryMin' in body.patch.preferences)d.preferences.salary_min=next.preferences.salaryMin;if('include_adjacent' in body.patch.preferences)d.preferences.include_adjacent=next.preferences.include_adjacent;if('opportunityTypes' in body.patch.preferences)d.preferences.job_types=next.preferences.opportunityTypes.map(x=>({'full-time':'Full-time','internship':'Internship'}[x]||x));if('include_adjacent' in body.patch.preferences)d.preferences.include_adjacent=next.preferences.include_adjacent;if('opportunityTypes' in body.patch.preferences)d.preferences.job_types=next.preferences.opportunityTypes.map(x=>({'full-time':'Full-time','internship':'Internship'}[x]||x));}
    const queued=[],syncChanged=JSON.stringify(facts(previous))!==JSON.stringify(facts(next));
    if(syncChanged)for(const a of d.service_accounts.filter(a=>a.enabled!==false&&a.status!=='paused')){for(const t of d.sync_tasks.filter(t=>t.provider===a.provider&&!['completed','synced'].includes(t.status)))t.status='superseded';const t={id:crypto.randomUUID(),provider:a.provider,profile_revision:next.revision,status:a.status==='needs_login'?'needs_login':'needs_action',payload:facts(next),created_at:stamp(),note:'Browser-assisted update required; verify authorization answers yourself.'};d.sync_tasks.push(t);a.status=t.status;queued.push(t);}
    else for(const t of d.sync_tasks.filter(t=>!['completed','synced','superseded'].includes(t.status)))t.profile_revision=next.revision;
    return {profile:next,changedFields,staleReviews:fitChanged,syncTasks:queued};
  }
  function account(d,b){if(!d.job_services.some(s=>s.id===b.provider)||!['needs_action','needs_login','ready','paused'].includes(b.status))throw Error('Invalid service account');if(b.profileUrl){const u=new URL(b.profileUrl);if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid profile URL');}if(b.provider==='interstride'&&b.enabled&&!b.availabilityConfirmed)throw Error('Confirm university access first');let a=d.service_accounts.find(x=>x.provider===b.provider);if(!a){a={provider:b.provider,enabled:false};d.service_accounts.push(a);}Object.assign(a,{status:b.status,profileUrl:b.profileUrl||'',accountExists:b.accountExists??null,enabled:b.enabled??a.enabled,availabilityConfirmed:b.availabilityConfirmed??a.availabilityConfirmed,updated_at:stamp()});if(a.enabled&&a.status!=='paused'&&!d.sync_tasks.some(t=>t.provider===a.provider&&t.profile_revision===d.profile.revision))d.sync_tasks.push({id:crypto.randomUUID(),provider:a.provider,profile_revision:d.profile.revision,status:'needs_action',payload:facts(d.profile),created_at:stamp()});return a;}
  function complete(d,b){const t=d.sync_tasks.find(t=>t.id===b.task_id),a=d.service_accounts.find(a=>a.provider===t?.provider);if(!t||!a||a.status==='paused'||a.enabled===false||t.status==='superseded'||b.profile_revision!==d.profile.revision||t.profile_revision!==b.profile_revision)throw Error('This update is paused or belongs to an old profile revision.');if(typeof b.evidence!=='string'||!b.evidence.trim()||b.evidence.length>4000)throw Error('Update evidence is required');t.status='completed';t.evidence=b.evidence;t.completed_at=stamp();a.status='synced';a.lastSyncedRevision=b.profile_revision;return t;}
  function events(d,b){const j=d.jobs.find(j=>j.id===b.job_id);if(!j||!['shown','selected','applied','incorrect'].includes(b.kind))throw Error('Invalid source outcome');const sources=new Set([j.source_id,j.discovered_source_id,...Object.keys(j.source_sightings||{})].filter(Boolean));for(const source_id of sources)if(!d.source_events.some(e=>e.job_id===j.id&&e.source_id===source_id&&e.kind===b.kind))d.source_events.push({job_id:j.id,source_id,kind:b.kind,created_at:stamp()});return {saved:true};}
  function stats(d){const result={};for(const e of d.source_events){result[e.source_id]??={shown:0,selected:0,applied:0,incorrect:0};result[e.source_id][e.kind]++;}return result;}
  window.WorkspaceState={init,saveProfile,account,complete,events,stats,validate};
})();
